development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  google_client_id: 192438685620-4vs7v0sau7g5bfcajeulvje18jdugo38.apps.googleusercontent.com
  google_client_secret: Y_II7Bsezu8bsOZ-ytw6isYM

  PAYJP_PRIVATE_KEY: sk_test_10114eafe2605308cd83bd02
  PAYJP_KEY: pk_test_c1014bdfe3f96e69dbe2b0a2