development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  google_client_id: <%= ENV["GOOGLE_CLIENT_ID"] %>
  google_client_secret: <%= ENV["GOOGLE_CLIENT_SECRET"] %>

production:
  PAYJP_PRIVATE_KEY: <%= ENV["PAYJP_PRIVATE_KEY"] %>
  PAYJP_KEY: <%= ENV["PAYJP_KEY"] %>